FROM gcr.io/tensorflow/tensorflow

RUN echo -n | openssl s_client -connect get.docker.io:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | tee '/usr/local/share/ca-certificates/get_docker_io.crt'

RUN update-ca-certificates
RUN apt-get update

RUN apt-get install -y python-opencv
RUN ln /dev/null /dev/raw1394
