#!/bin/bash
# rem
# Script de install/start do Reminiscence.

source env.sh

function server-install-msg-error
{
	echo $SERVER_MSG_ERROR
}

function server-install-or-start-help
{
	echo -e "Uso: rem [--cpu [--build | --bash] | --gpu [--build | --bash] | --help | --sf]"
	echo -e "Opções:"
	echo -e "\t--help\t\tMostra informações de ajuda."
	echo -e "\t--sf\t\tPermite que o usuário HOST consiga ler/escrever/executar na pasta compartilhada."
	echo -e "\t--cpu\t\tInstala/Inicia servidor com suporte somente para CPU."
	echo -e "\t--gpu\t\tInstala/Inicia servidor com suporte a GPU.\n"
	echo -e "Exemplos:"
	echo -e "\trem --cpu\t\tInstala ou Inicia o servidor do Reminiscence para CPU, somente."
	echo -e "\trem --gpu\t\tInstala ou Inicia o servidor do Reminescence com suporte a GPU NVIDIA."
	echo -e "\trem --gpu --build\tConstrói o servidor novamente a partir do arquivo Dockerfile_gpu."
	echo -e "\trem --gpu --bash\tExecuta um terminal (TTY) para interagir com o servidor."
}

function server-install-or-start-sf
{
	eval $TENSORFLOW_SF_USR
}

function server-install-or-start-gpu
{
	# Instale o nvidia-docker caso o utilitário não esteja instalado.
	if ! type "nvidia-docker" > /dev/null; then
		eval $NVIDIA_DOCKER_INSTALLER
	fi
	
	eval $TENSORFLOW_START_SERVER $1 $2
}

function server-install-or-start-cpu
{
	eval $TENSORFLOW_START_SERVER $1 $2
}

function server-build
{
	eval $TENSORFLOW_BUILD $1 $2
}

function server-exec-bash
{
	eval $DOCKER_EXEC_BASH
}


function funcs_arg_2
{
	ARG_2=$3
	
	case "$2" in
		$TENSORFLOW_SERVER_ARG2_BUILD)
			server-build $1 $ARG_2
			exit 0
			;;
			
		$TENSORFLOW_SERVER_ARG2_BASH)
			server-exec-bash
			exit 0
			;;
	esac
}

function reminiscence
{
	# Se o terceiro argumento tiver algo escrito, pare o script.
	if [[ !(-z "${3+set}") ]]; then
		server-install-msg-error
		exit 1
	fi
	
	case "$1" in
		$REM_INSTALL_START_ARG_HELP)
			if [[ !(-z "${2+set}") ]]; then
				server-install-msg-error
				exit 1
			fi
			
			server-install-or-start-help
			;;
			
		$TENSORFLOW_SERVER_ARG1_SF)
			if [[ !(-z "${2+set}") ]]; then
				server-install-msg-error
				exit 1
			fi
		
			server-install-or-start-sf
			;;
			
		$TENSORFLOW_SERVER_ARG1_GPU)
			funcs_arg_2 $1 $2 $3
			server-install-or-start-gpu $1 $2
			;;
			
		$TENSORFLOW_SERVER_ARG1_CPU)
			funcs_arg_2 $1 $2 $3
			server-install-or-start-cpu $1 $2
			;;
			
		*)
			server-install-or-start-help
			exit 1
	esac
}

reminiscence $1 $2 $3

